# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50c9ac53b07e7f46193bf71b46bd83f5690554d599ee36bf8db6236730d93b3fb5f564393f7317b79167911d0ab70a3f8a221a2b63a52f45326809ecc985d743

test:
  secret_key_base: aa91418aee705e008073413f406224efbcc7ea03ac60b4ac271a205c9b61c75706f9788f171b31f0ec75c4e22483f0931473bd6fd6748b5c5f14f02db0ce33c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
